import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={inter.className}>
      <header className="bg-emerald-800  flex justify-between max-w-6xl mx-auto">
        <h4>About NavLogo</h4>
        <nav>
          <ul className="flex gap-4 justify-end px-4 text-black items-center">
            <li>About Infra</li>
            <li>About Location</li>
          </ul>
        </nav>
      </header>
      {children}
    </div>
  );
}
