import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create  App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-slate-100  flex justify-between max-w-6xl mx-auto">
          <img
            src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/32877/logo-thing.png"
            alt="headerLogo"
            className="w-24"
          />
          <nav>
            <ul className="flex gap-4 justify-end px-4 text-black items-center">
              <li>
                <Link href={"/"}>Home</Link>
              </li>
              <li>
                <Link href={"/users"}>Users</Link>
              </li>
              <li>
                <Link href={"/users-ssg"}>Users-SSG_ISR</Link>
              </li>
              <li>About</li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
